<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PlantSeeder extends Seeder
{
    public function run(): void
    {
        // family_id map: Araceae=1, Cactaceae=2, Rosaceae=3, Lamiaceae=4, Asteraceae=5,
        // Fabaceae=6, Liliaceae=7, Orchidaceae=8, Euphorbiaceae=9, Moraceae=10,
        // Rutaceae=11, Apocynaceae=12, Arecaceae=13, Bromeliaceae=14, Myrtaceae=15

        $plants = [
            // --- Araceae ---
            [
                'name'                 => 'Monstera Deliciosa',
                'family_id'            => 1,
                'about_description'    => 'The Monstera Deliciosa, commonly known as the Swiss Cheese Plant, is an icon of indoor gardening. Famous for its large, heart-shaped leaves that develop dramatic holes (fenestrations) as they mature, it brings an instant tropical vibe to any space. Native to the rainforests of Southern Mexico and Panama, it thrives in bright, indirect light and well-draining soil.',
                'light_need'           => 'Bright, indirect sunlight',
                'watering'             => 'Every 1-2 weeks',
                'temperature'          => '18°C - 30°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Avoid direct hot afternoon sun as it can burn the leaves. Filtered morning light is ideal.',
                'leaf_care'            => 'Wipe leaves with a damp cloth every few weeks to keep them dust-free and shiny.',
                'support_instructions' => 'As a climber, it loves a moss pole to attach its aerial roots to for stability.',
                'is_primary'           => true,
            ],
            [
                'name'                 => 'Philodendron Imperial Green',
                'family_id'            => 1,
                'about_description'    => 'A lush, compact philodendron with large, glossy dark-green leaves. Perfect for beginners and low-light rooms. Native to the tropical rainforests of South America, it adapts well to indoor conditions and grows in a beautiful rosette form.',
                'light_need'           => 'Low to bright indirect light',
                'watering'             => 'Every 1-2 weeks',
                'temperature'          => '18°C - 28°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Keep away from direct sunlight. Thrives in shade or dappled light.',
                'leaf_care'            => 'Clean leaves monthly with a damp cloth to remove dust and improve photosynthesis.',
                'support_instructions' => 'No support needed. Self-standing rosette shape.',
                'is_primary'           => false,
            ],
            [
                'name'                 => 'Pothos Aureus',
                'family_id'            => 1,
                'about_description'    => 'One of the easiest and most forgiving houseplants. Its trailing vines with heart-shaped yellow-green marbled leaves look stunning in hanging baskets or on shelves. Extremely tolerant of low light and irregular watering.',
                'light_need'           => 'Low to bright indirect light',
                'watering'             => 'Every 1-2 weeks, allow soil to dry out between waterings',
                'temperature'          => '15°C - 30°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Tolerates low light but grows faster in bright indirect light.',
                'leaf_care'            => 'Occasional dusting with a soft cloth.',
                'support_instructions' => 'Can be trained to climb a pole or left to trail from a shelf.',
                'is_primary'           => false,
            ],
            [
                'name'                 => 'Spathiphyllum (Peace Lily)',
                'family_id'            => 1,
                'about_description'    => 'The Peace Lily is a graceful indoor plant with white hood-like flowers and glossy dark green leaves. Known for its air-purifying qualities, it is ideal for bedrooms and offices. It communicates thirst by drooping slightly, then perks right back up after watering.',
                'light_need'           => 'Low to medium indirect light',
                'watering'             => 'Every 1 week, keep soil slightly moist',
                'temperature'          => '18°C - 27°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Avoid direct sun. Perfect for north-facing rooms.',
                'leaf_care'            => 'Remove yellow leaves promptly. Wipe with a damp cloth.',
                'support_instructions' => 'No support required.',
                'is_primary'           => false,
            ],

            // --- Cactaceae ---
            [
                'name'                 => 'Cactus Opuntia (Figuier de Barbarie)',
                'family_id'            => 2,
                'about_description'    => 'The Prickly Pear cactus is iconic across Morocco, found in gardens, hedges, and roadsides. Its flat green pads store water, and it produces edible red-orange fruit called "Hindi" locally. Extremely drought-tolerant and decorative.',
                'light_need'           => 'Full sun',
                'watering'             => 'Every 3-4 weeks in summer, very rarely in winter',
                'temperature'          => '10°C - 40°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Needs maximum direct sun exposure.',
                'leaf_care'            => 'Remove dead pads with tongs. Handle spines with care.',
                'support_instructions' => 'Freestanding. Plant in sandy, well-draining soil.',
                'is_primary'           => true,
            ],
            [
                'name'                 => 'Cereus Peruvianus',
                'family_id'            => 2,
                'about_description'    => 'A tall, columnar blue-green cactus that can reach several meters. Very easy to care for and makes a striking architectural statement indoors or outdoors in warm Moroccan climates.',
                'light_need'           => 'Full sun to bright indirect light',
                'watering'             => 'Every 2-3 weeks in summer, monthly in winter',
                'temperature'          => '10°C - 38°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Place near a south-facing window or outdoors in full sun.',
                'leaf_care'            => 'No leaves. Remove debris from around the base.',
                'support_instructions' => 'May need staking when very tall.',
                'is_primary'           => false,
            ],

            // --- Rosaceae ---
            [
                'name'                 => 'Rosa Damascena (Rose de Damas)',
                'family_id'            => 3,
                'about_description'    => 'The Damask Rose is celebrated across Morocco, especially in the Kelaat M\'Gouna valley known as the Valley of Roses. Used for rose water, perfume, and cosmetics, its intensely fragrant pink blooms are harvested each spring.',
                'light_need'           => 'Full sun (6+ hours)',
                'watering'             => 'Every 2-3 days in summer, weekly in winter',
                'temperature'          => '5°C - 30°C',
                'pet_friendly'         => true,
                'sun_exposure'         => 'Requires full sun for optimal blooming.',
                'leaf_care'            => 'Watch for black spot fungus. Remove infected leaves immediately.',
                'support_instructions' => 'Train on a trellis or arch for climbing varieties.',
                'is_primary'           => true,
            ],
            [
                'name'                 => 'Prunus Persica (Pêcher)',
                'family_id'            => 3,
                'about_description'    => 'The peach tree is widely grown in Moroccan home gardens, particularly in Fez and Meknès regions. It produces sweet, fuzzy fruits in summer and beautiful pink blossoms in late winter.',
                'light_need'           => 'Full sun',
                'watering'             => 'Regular watering, especially during fruit development',
                'temperature'          => '-5°C - 35°C',
                'pet_friendly'         => true,
                'sun_exposure'         => 'Plant in an open, sunny spot with good air circulation.',
                'leaf_care'            => 'Monitor for peach leaf curl fungus. Apply copper fungicide in autumn.',
                'support_instructions' => 'Stake young trees for their first two years.',
                'is_primary'           => false,
            ],

            // --- Lamiaceae ---
            [
                'name'                 => 'Lavandula (Lavande)',
                'family_id'            => 4,
                'about_description'    => 'Lavender is beloved in Moroccan gardens and riads for its calming fragrance and purple flower spikes. Easy to grow in the hot, dry Moroccan climate, it attracts bees and butterflies and is used in traditional remedies.',
                'light_need'           => 'Full sun',
                'watering'             => 'Every 2 weeks once established, drought-tolerant',
                'temperature'          => '5°C - 35°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Thrives in full sun. Avoid shaded or humid spots.',
                'leaf_care'            => 'Prune after flowering to keep compact shape.',
                'support_instructions' => 'No support needed. Plant in raised beds for drainage.',
                'is_primary'           => true,
            ],
            [
                'name'                 => 'Mentha (Menthe Nana)',
                'family_id'            => 4,
                'about_description'    => 'Moroccan Mint (Nana) is the essential ingredient in iconic Moroccan mint tea. Highly aromatic with bright green leaves, it is one of the most cultivated herbs across the country. Grows vigorously and spreads quickly.',
                'light_need'           => 'Full sun to partial shade',
                'watering'             => 'Keep soil consistently moist, every 1-2 days in summer',
                'temperature'          => '15°C - 30°C',
                'pet_friendly'         => true,
                'sun_exposure'         => 'Tolerates some afternoon shade in very hot areas.',
                'leaf_care'            => 'Harvest regularly to encourage bushy growth and prevent flowering.',
                'support_instructions' => 'Plant in pots to control spreading. No staking needed.',
                'is_primary'           => false,
            ],

            // --- Asteraceae ---
            [
                'name'                 => 'Helianthus Annuus (Tournesol)',
                'family_id'            => 5,
                'about_description'    => 'The sunflower is a cheerful annual grown widely in Morocco, both as an ornamental and a commercial crop for its oil-rich seeds. Its large golden heads follow the sun throughout the day in a process called heliotropism.',
                'light_need'           => 'Full sun (8+ hours)',
                'watering'             => 'Every 2-3 days, deeply',
                'temperature'          => '15°C - 35°C',
                'pet_friendly'         => true,
                'sun_exposure'         => 'Plant in the most open, sunny position in the garden.',
                'leaf_care'            => 'Remove lower leaves if mildew develops for air circulation.',
                'support_instructions' => 'Stake tall varieties when they exceed 1.5 metres.',
                'is_primary'           => true,
            ],
            [
                'name'                 => 'Calendula Officinalis (Souci)',
                'family_id'            => 5,
                'about_description'    => 'A cheerful, easy-to-grow annual with orange or yellow daisy-like flowers. Widely used in Moroccan traditional medicine for its anti-inflammatory properties. Blooms from late autumn through spring in the Moroccan climate.',
                'light_need'           => 'Full sun to partial shade',
                'watering'             => 'Every 3-4 days',
                'temperature'          => '5°C - 25°C',
                'pet_friendly'         => true,
                'sun_exposure'         => 'Prefers a cool, sunny position. Ideal for winter/spring gardens.',
                'leaf_care'            => 'Deadhead spent flowers regularly to prolong blooming.',
                'support_instructions' => 'No support needed.',
                'is_primary'           => false,
            ],

            // --- Fabaceae ---
            [
                'name'                 => 'Ceratonia Siliqua (Caroubier)',
                'family_id'            => 6,
                'about_description'    => 'The Carob tree is a slow-growing Mediterranean evergreen tree found throughout Morocco. It produces long brown pods that are used as a natural sweetener and in traditional food. Extremely drought-hardy and long-lived.',
                'light_need'           => 'Full sun',
                'watering'             => 'Very drought-tolerant once established, water monthly',
                'temperature'          => '5°C - 40°C',
                'pet_friendly'         => true,
                'sun_exposure'         => 'Thrives in full Mediterranean sun.',
                'leaf_care'            => 'Minimal maintenance. Remove dead branches in winter.',
                'support_instructions' => 'Stake young trees. No support needed once mature.',
                'is_primary'           => true,
            ],
            [
                'name'                 => 'Acacia Melanoxylon (Acacia)',
                'family_id'            => 6,
                'about_description'    => 'Acacias are prevalent in Moroccan landscapes, from the Saharan south to the Atlantic coast. They provide shade and shelter in arid areas and fix nitrogen in the soil, improving fertility.',
                'light_need'           => 'Full sun',
                'watering'             => 'Drought-tolerant, water every 2-3 weeks',
                'temperature'          => '10°C - 42°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Needs maximum sun exposure.',
                'leaf_care'            => 'Prune lower branches to raise canopy for shade.',
                'support_instructions' => 'Stake young trees for the first 2 years.',
                'is_primary'           => false,
            ],

            // --- Orchidaceae ---
            [
                'name'                 => 'Phalaenopsis (Orchidée Papillon)',
                'family_id'            => 8,
                'about_description'    => 'The Moth Orchid is the world\'s most popular orchid, prized for its elegant sprays of butterfly-like flowers in white, pink, or purple. It thrives on neglect and can rebloom multiple times per year under the right conditions.',
                'light_need'           => 'Bright indirect light',
                'watering'             => 'Every 1-2 weeks, ice cube method or light soaking',
                'temperature'          => '18°C - 29°C',
                'pet_friendly'         => true,
                'sun_exposure'         => 'East-facing window is ideal. Avoid direct afternoon sun.',
                'leaf_care'            => 'Wipe leaves with a slightly damp cloth. No spraying on flowers.',
                'support_instructions' => 'Use a bamboo stake to support flower spikes as they grow.',
                'is_primary'           => true,
            ],

            // --- Euphorbiaceae ---
            [
                'name'                 => 'Euphorbia Pulcherrima (Poinsettia)',
                'family_id'            => 9,
                'about_description'    => 'The Poinsettia dazzles with its brilliant red bracts (often mistaken for flowers) surrounding tiny yellow flowers. A popular ornamental in Moroccan homes especially during winter festivities. The white milky sap is a mild irritant.',
                'light_need'           => 'Bright indirect light',
                'watering'             => 'Every 1 week, allow surface to dry between waterings',
                'temperature'          => '15°C - 22°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Needs bright light but avoid harsh direct sun which fades bracts.',
                'leaf_care'            => 'Avoid cold drafts. Keep away from air conditioning vents.',
                'support_instructions' => 'No support needed. Prune after flowering season.',
                'is_primary'           => false,
            ],

            // --- Moraceae ---
            [
                'name'                 => 'Ficus Benjamina (Ficus Pleureur)',
                'family_id'            => 10,
                'about_description'    => 'One of the most classic indoor trees, the Weeping Fig adds a graceful, elegant touch to any living space with its arching branches and small glossy leaves. Commonly found in Moroccan homes and hotel lobbies.',
                'light_need'           => 'Bright indirect light',
                'watering'             => 'Every 1 week, keep soil evenly moist',
                'temperature'          => '16°C - 30°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Sensitive to position changes - avoid moving once settled.',
                'leaf_care'            => 'Leaf drop occurs with draughts or temperature changes. Wipe leaves monthly.',
                'support_instructions' => 'Needs a stable position. No staking required.',
                'is_primary'           => true,
            ],
            [
                'name'                 => 'Ficus Carica (Figuier)',
                'family_id'            => 10,
                'about_description'    => 'The Fig tree is deeply embedded in Moroccan culture and cuisine. Its sweet fruits are eaten fresh or dried, while the leaves provide dense shade. Grows spontaneously in many Moroccan gardens and ruins.',
                'light_need'           => 'Full sun',
                'watering'             => 'Once established, water every 1-2 weeks. Drought-tolerant.',
                'temperature'          => '5°C - 40°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Loves heat and direct sun. Perfect for south-facing walls.',
                'leaf_care'            => 'Prune in late winter to shape and encourage fruiting.',
                'support_instructions' => 'Train against a wall for espalier effect. Stake when young.',
                'is_primary'           => false,
            ],

            // --- Rutaceae ---
            [
                'name'                 => 'Citrus Sinensis (Oranger)',
                'family_id'            => 11,
                'about_description'    => 'The Sweet Orange tree is ubiquitous in Morocco and the iconic Marrakech streetscapes. Souss-Massa region produces the famous Moroccan oranges. Fragrant white blossoms perfume entire neighbourhoods in spring.',
                'light_need'           => 'Full sun',
                'watering'             => 'Every 3-4 days in summer, weekly in winter',
                'temperature'          => '10°C - 38°C',
                'pet_friendly'         => true,
                'sun_exposure'         => 'Requires full sun for fruit production.',
                'leaf_care'            => 'Monitor for scale insects and citrus leaf miner.',
                'support_instructions' => 'Stake young trees. Prune crossing branches annually.',
                'is_primary'           => true,
            ],
            [
                'name'                 => 'Citrus Limon (Citronnier)',
                'family_id'            => 11,
                'about_description'    => 'The lemon tree is a staple of Moroccan cooking and preserved as the famous pickled "citron confit". It grows well in pots and gardens across Morocco, producing fruit almost year-round in warm coastal climates.',
                'light_need'           => 'Full sun',
                'watering'             => 'Every 3-4 days in summer, weekly in winter',
                'temperature'          => '10°C - 38°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'South-facing wall or open sunny position.',
                'leaf_care'            => 'Yellow leaves indicate overwatering or iron deficiency. Treat accordingly.',
                'support_instructions' => 'Stake young trees. No support needed once established.',
                'is_primary'           => false,
            ],

            // --- Apocynaceae ---
            [
                'name'                 => 'Nerium Oleander (Laurier-Rose)',
                'family_id'            => 12,
                'about_description'    => 'Oleander is one of Morocco\'s most striking ornamental shrubs, lining roads and adorning public gardens. It blooms abundantly in pink, red, or white. While beautiful, all parts are toxic if ingested.',
                'light_need'           => 'Full sun',
                'watering'             => 'Drought-tolerant once established, water every 2 weeks',
                'temperature'          => '5°C - 42°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Thrives in full, intense Moroccan sun.',
                'leaf_care'            => 'Prune after flowering. Wear gloves as sap is toxic.',
                'support_instructions' => 'Can be trained as a tree or left as a multi-stemmed shrub.',
                'is_primary'           => true,
            ],
            [
                'name'                 => 'Plumeria Rubra (Frangipanier)',
                'family_id'            => 12,
                'about_description'    => 'The Frangipani is prized for its intoxicating fragrance and beautiful waxy flowers in white, yellow, and pink. It thrives in Morocco\'s warm coastal cities like Agadir and Casablanca, producing its iconic tropical blooms from spring to autumn.',
                'light_need'           => 'Full sun',
                'watering'             => 'Every 1-2 weeks in summer, minimal in winter (dormant)',
                'temperature'          => '15°C - 38°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Maximum sun exposure is essential for flowering.',
                'leaf_care'            => 'Leaves drop in winter - this is normal dormancy.',
                'support_instructions' => 'Plant in well-draining sandy soil. Stake young plants.',
                'is_primary'           => false,
            ],

            // --- Arecaceae ---
            [
                'name'                 => 'Phoenix Dactylifera (Palmier Dattier)',
                'family_id'            => 13,
                'about_description'    => 'The Date Palm is Morocco\'s most iconic tree, a symbol of the south and the Saharan oases. Draa Valley and Tafilalt produce world-famous dates. A single palm can live for over 100 years and produce hundreds of kilos of dates annually.',
                'light_need'           => 'Full sun',
                'watering'             => 'Drought-tolerant once established, deep water monthly',
                'temperature'          => '0°C - 50°C',
                'pet_friendly'         => true,
                'sun_exposure'         => 'Maximum desert sun. Intolerant of shade.',
                'leaf_care'            => 'Remove dead fronds annually. Harvest dates in autumn.',
                'support_instructions' => 'No support needed for mature palms. Stake for the first year.',
                'is_primary'           => true,
            ],
            [
                'name'                 => 'Chamaerops Humilis (Palmier Nain)',
                'family_id'            => 13,
                'about_description'    => 'The Dwarf Fan Palm is native to Morocco and the only palm indigenous to Europe. Growing wild in the Rif and Atlas foothills, it forms dense multi-stemmed clumps with fan-shaped leaves and is highly ornamental for gardens.',
                'light_need'           => 'Full sun to partial shade',
                'watering'             => 'Every 2-3 weeks once established',
                'temperature'          => '-5°C - 42°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Very adaptable; tolerates coastal winds and drought.',
                'leaf_care'            => 'Remove old dead fronds at the base annually.',
                'support_instructions' => 'No support needed. Natural clumping habit.',
                'is_primary'           => false,
            ],

            // --- Bromeliaceae ---
            [
                'name'                 => 'Ananas Comosus (Ananas Ornemental)',
                'family_id'            => 14,
                'about_description'    => 'The ornamental pineapple plant is a striking tropical plant with stiff rosettes of spiny leaves topped by a miniature pineapple. Grown as a houseplant in Morocco, it adds an exotic, architectural appeal to interior spaces.',
                'light_need'           => 'Bright indirect to direct light',
                'watering'             => 'Water into the central cup and soil every 2 weeks',
                'temperature'          => '18°C - 30°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Bright light encourages fruiting. Avoid deep shade.',
                'leaf_care'            => 'Keep the central cup filled with fresh water. Clean leaves monthly.',
                'support_instructions' => 'No support needed. Freestanding rosette.',
                'is_primary'           => false,
            ],

            // --- Myrtaceae ---
            [
                'name'                 => 'Eucalyptus Globulus (Eucalyptus)',
                'family_id'            => 15,
                'about_description'    => 'Eucalyptus trees were introduced to Morocco in the early 20th century and are now found everywhere, from coastal forests to the Middle Atlas. Famous for their fast growth, medicinal leaves used for respiratory remedies, and aromatic menthol fragrance.',
                'light_need'           => 'Full sun',
                'watering'             => 'Drought-tolerant once established, water bi-monthly',
                'temperature'          => '-5°C - 45°C',
                'pet_friendly'         => false,
                'sun_exposure'         => 'Needs full sun. Very fast-growing in open positions.',
                'leaf_care'            => 'Harvest young branches for medicinal use. Prune to shape.',
                'support_instructions' => 'Stake firmly when young as they grow very quickly and can be top-heavy.',
                'is_primary'           => true,
            ],
            [
                'name'                 => 'Myrtus Communis (Myrte)',
                'family_id'            => 15,
                'about_description'    => 'Myrtle is a fragrant evergreen shrub with glossy dark leaves, white star-shaped flowers, and dark berries. Deeply rooted in Moroccan culture, its leaves are traditionally used in wedding ceremonies and hammam body scrubs.',
                'light_need'           => 'Full sun',
                'watering'             => 'Every 1-2 weeks, keep soil slightly moist',
                'temperature'          => '0°C - 35°C',
                'pet_friendly'         => true,
                'sun_exposure'         => 'Loves full Mediterranean sun. Tolerates coastal conditions.',
                'leaf_care'            => 'Prune after flowering to maintain a neat, compact shape.',
                'support_instructions' => 'Can be clipped as topiary. No support needed.',
                'is_primary'           => false,
            ],
        ];

        foreach ($plants as $plant) {
            DB::table('plants')->insert([
                'name'                 => $plant['name'],
                'slug'                 => Str::slug($plant['name']),
                'family_id'            => $plant['family_id'],
                'about_description'    => $plant['about_description'],
                'light_need'           => $plant['light_need'],
                'watering'             => $plant['watering'],
                'temperature'          => $plant['temperature'],
                'pet_friendly'         => $plant['pet_friendly'],
                'sun_exposure'         => $plant['sun_exposure'],
                'leaf_care'            => $plant['leaf_care'],
                'support_instructions' => $plant['support_instructions'],
                'is_primary'           => $plant['is_primary'],
                'created_at'           => now(),
                'updated_at'           => now(),
            ]);
        }
    }
}
